site_name: Документация
site_url: https://polekhina01.github.io/  
site_description: Автоматически генерируемая документация

repo_url: https://github.com/polekhina01/polekhina01.github.io  
repo_name: polekhina01/polekhina01.github.io

theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Документы:
      - 10-23_КП-П-ПЗ:
          - 0_Титульный_лист_МТ: 10-23_КП-П-ПЗ/0_Титульный_лист_МТ.md
          - 1_Справка_ГИПа-2021.03.17: 10-23_КП-П-ПЗ/1_Справка_ГИПа-2021.03.17.md
          - 2_Содержание_МТ-2021.11.17: 10-23_КП-П-ПЗ/2_Содержание_МТ-2021.11.17.md
          - 3_Пояснительная_записка_КПЛН_МТ_2024.06.28: 10-23_КП-П-ПЗ/3_Пояснительная_записка_КПЛН_МТ_2024.06.28.md
      - 1076-01-ПЗ1:
          - 1076-01-ПЗ1_: 1076-01-ПЗ1/1076-01-ПЗ1_.md
          - 1076-01-ПЗ1_cleaned: 1076-01-ПЗ1/1076-01-ПЗ1_cleaned.md
          - 20231117_З≠П_Эв†ѓ2_ver1: 1076-01-ПЗ1/20231117_З≠П_Эв†ѓ2_ver1.md
          - ~$76-01-ПЗ2_rev1_ver4: 1076-01-ПЗ1/~$76-01-ПЗ2_rev1_ver4.md
          - Т†°Ђ®ж† ®Іђ.1 1076-01-ПЗ1: 1076-01-ПЗ1/Т†°Ђ®ж† ®Іђ.1 1076-01-ПЗ1.md
      - 1076-01-ПЗ2:
          - 1076-01-ПЗ2_cleaned: 1076-01-ПЗ2/1076-01-ПЗ2_cleaned.md
          - 1076-01-ПЗ2_rev2: 1076-01-ПЗ2/1076-01-ПЗ2_rev2.md
      - 1256-30-ПЗ1:
          - 1256-30-ПЗ1. СП: 1256-30-ПЗ1/1256-30-ПЗ1. СП.md
          - 1256-30-ПЗ1_titul_Sign_cleaned: 1256-30-ПЗ1/1256-30-ПЗ1_titul_Sign_cleaned.md
          - 1256-30-ПЗ1_бЃ§•а¶†≠®•_cleaned: 1256-30-ПЗ1/1256-30-ПЗ1_бЃ§•а¶†≠®•_cleaned.md
          - Влѓ®б™† НОПРИЗ РЃђ†≠ЃҐб™†п_cleaned: 1256-30-ПЗ1/Влѓ®б™† НОПРИЗ РЃђ†≠ЃҐб™†п_cleaned.md
      - 1256-30-ПЗ2:
          - 1256-30-ПЗ2: 1256-30-ПЗ2/1256-30-ПЗ2.md
          - 1256-30-ПЗ2_cleaned: 1256-30-ПЗ2/1256-30-ПЗ2_cleaned.md
          - 1256-30-ПЗ2_titul_Sign_cleaned: 1256-30-ПЗ2/1256-30-ПЗ2_titul_Sign_cleaned.md
      - 1256-30-ПЗ3:
          - 0869_РФ-О-РСПИ_ХЃ§л≠б™®© °-а, гз. 6.2_cleaned: 1256-30-ПЗ3/0869_РФ-О-РСПИ_ХЃ§л≠б™®© °-а, гз. 6.2_cleaned.md
          - 1256-30-ПЗ3.1: 1256-30-ПЗ3/1256-30-ПЗ3.1.md
          - 1256-30-ПЗ3.1_titul_Sign_cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.1_titul_Sign_cleaned.md
          - 1256-30-ПЗ3.1_бЃ§•а¶†≠®•_cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.1_бЃ§•а¶†≠®•_cleaned.md
          - 1256-30-ПЗ3.2: 1256-30-ПЗ3/1256-30-ПЗ3.2.md
          - 1256-30-ПЗ3.2_titul_Sign_cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.2_titul_Sign_cleaned.md
          - 1256-30-ПЗ3.2_бЃ§•а¶†≠®•_cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.2_бЃ§•а¶†≠®•_cleaned.md
          - 1256_ЗНП §Ђп МГЭ: 1256-30-ПЗ3/1256_ЗНП §Ђп МГЭ.md
          - 1256_ЗНП §Ђп МГЭ_cleaned: 1256-30-ПЗ3/1256_ЗНП §Ђп МГЭ_cleaned.md
          - 1256_ЗНП §Ђп МГЭ_в®вгЂ - ѓЃ§ѓ®б†≠_cleaned: 1256-30-ПЗ3/1256_ЗНП §Ђп МГЭ_в®вгЂ - ѓЃ§ѓ®б†≠_cleaned.md
          - 16-13-3322®™Ѓѓ_cleaned: 1256-30-ПЗ3/16-13-3322®™Ѓѓ_cleaned.md
          - 230818_ДЃ£. †а•≠§л ЗУ 17079 С™®д-И≠Ґ•бв_cleaned: 1256-30-ПЗ3/230818_ДЃ£. †а•≠§л ЗУ 17079 С™®д-И≠Ґ•бв_cleaned.md
          - 230823_Сѓа†Ґ™† Ѓ дЃ≠ЃҐле ™Ѓ≠ж•≠ва†ж®пе_cleaned: 1256-30-ПЗ3/230823_Сѓа†Ґ™† Ѓ дЃ≠ЃҐле ™Ѓ≠ж•≠ва†ж®пе_cleaned.md
          - 230823_Сѓа†Ґ™† Ѓ ™Ђ®ђ†в®з•б™Ѓ© е†а†™в•а®бв®™•_cleaned: 1256-30-ПЗ3/230823_Сѓа†Ґ™† Ѓ ™Ђ®ђ†в®з•б™Ѓ© е†а†™в•а®бв®™•_cleaned.md
          - 230914_Сѓа†Ґ™† Ѓ° гбв†≠ЃҐЂ•≠≠ле СЗЗ_cleaned: 1256-30-ПЗ3/230914_Сѓа†Ґ™† Ѓ° гбв†≠ЃҐЂ•≠≠ле СЗЗ_cleaned.md
          - 230928_ТУ РЃбб•в® ь И-23-00-113433_102_cleaned: 1256-30-ПЗ3/230928_ТУ РЃбб•в® ь И-23-00-113433_102_cleaned.md
          - 231030_Сѓа†Ґ™† Ѓ° ®≠в•≠б®Ґ≠Ѓбв® §Ґ®¶•≠®п ва†≠бѓЃав†_cleaned: 1256-30-ПЗ3/231030_Сѓа†Ґ™† Ѓ° ®≠в•≠б®Ґ≠Ѓбв® §Ґ®¶•≠®п ва†≠бѓЃав†_cleaned.md
          - 231102_Влѓ®б™† ®І ЕГРН ≠† ЗУ 77 09 0005007 17079 б ®Ікпвлђ ™гб™Ѓђ_cleaned: 1256-30-ПЗ3/231102_Влѓ®б™† ®І ЕГРН ≠† ЗУ 77 09 0005007 17079 б ®Ікпвлђ ™гб™Ѓђ_cleaned.md
          - 231130_Н†£агІ™® ≠† Ѓд®бл (ЭОМ ѓа•§ЂЃ¶•≠®•): 1256-30-ПЗ3/231130_Н†£агІ™® ≠† Ѓд®бл (ЭОМ ѓа•§ЂЃ¶•≠®•).md
          - 231130_Н†£агІ™® ≠† Ѓд®бл (ЭОМ ѓа•§ЂЃ¶•≠®•)_cleaned: 1256-30-ПЗ3/231130_Н†£агІ™® ≠† Ѓд®бл (ЭОМ ѓа•§ЂЃ¶•≠®•)_cleaned.md
          - 240618_Н†£агІ™® ≠† Ѓ°й•бвҐ•≠≠л• ѓЃђ•й•≠®п (ЭОМ)_cleaned: 1256-30-ПЗ3/240618_Н†£агІ™® ≠† Ѓ°й•бвҐ•≠≠л• ѓЃђ•й•≠®п (ЭОМ)_cleaned.md
          - 240624_КС-ПРО МГЭ - ®≠дЃ Ѓ б≠Ѓб•_cleaned: 1256-30-ПЗ3/240624_КС-ПРО МГЭ - ®≠дЃ Ѓ б≠Ѓб•_cleaned.md
          - ®бе. ь1314 Ѓв 11.06.2024_О ≠•вЃ™б®з≠Ѓбв® ѓа®ђ•≠п•ђле бваЃ© ђ†в•а®†ЂЃҐ ≠..._cleaned: 1256-30-ПЗ3/®бе. ь1314 Ѓв 11.06.2024_О ≠•вЃ™б®з≠Ѓбв® ѓа®ђ•≠п•ђле бваЃ© ђ†в•а®†ЂЃҐ ≠..._cleaned.md
          - АО _СКИФ ИНВЕСТ__НЃђ•а_ТУ_69850_Р•£_≠Ѓђ•а_ТУ_112-25-1488_24 (1)_cleaned: 1256-30-ПЗ3/АО _СКИФ ИНВЕСТ__НЃђ•а_ТУ_69850_Р•£_≠Ѓђ•а_ТУ_112-25-1488_24 (1)_cleaned.md
          - А™в б ѓа®ЂЃ¶•≠®пђ®_ХЃ§л≠б™®© °гЂмҐ†а Іг 6.2_cleaned: 1256-30-ПЗ3/А™в б ѓа®ЂЃ¶•≠®пђ®_ХЃ§л≠б™®© °гЂмҐ†а Іг 6.2_cleaned.md
          - Ба•≠§-Ђ®бв_cleaned: 1256-30-ПЗ3/Ба•≠§-Ђ®бв_cleaned.md
          - З†™Ђоз•≠®• ХЃ§л≠б™®© °гЂмҐ†а_cleaned: 1256-30-ПЗ3/З†™Ђоз•≠®• ХЃ§л≠б™®© °гЂмҐ†а_cleaned.md
          - КС-ѓаЃ ХЃ§л≠б™®© °гЂ. І-г 6-2_cleaned: 1256-30-ПЗ3/КС-ѓаЃ ХЃ§л≠б™®© °гЂ. І-г 6-2_cleaned.md
          - П®бмђЃ ДКН_cleaned: 1256-30-ПЗ3/П®бмђЃ ДКН_cleaned.md
          - Па®ЂЃ¶•≠®• 1_ТЗ. Па®ЂЃ¶•≠®• 1. Ба•≠§-Ђ®бв Ґ•а.3: 1256-30-ПЗ3/Па®ЂЃ¶•≠®• 1_ТЗ. Па®ЂЃ¶•≠®• 1. Ба•≠§-Ђ®бв Ґ•а.3.md
          - Па®ЂЃ¶•≠®• 1_ТЗ. Па®ЂЃ¶•≠®• 3.3. Н†£агІ™® КР: 1256-30-ПЗ3/Па®ЂЃ¶•≠®• 1_ТЗ. Па®ЂЃ¶•≠®• 3.3. Н†£агІ™® КР.md
          - ПаЃвЃ™ЃЂ ГЗК ХП_cleaned: 1256-30-ПЗ3/ПаЃвЃ™ЃЂ ГЗК ХП_cleaned.md
          - РФ-77-4-53-3-48-2024-0330-0-ГПЗУ_cleaned: 1256-30-ПЗ3/РФ-77-4-53-3-48-2024-0330-0-ГПЗУ_cleaned.md
          - СЃ£Ђ†бЃҐ†≠®• бваЃ®в•ЂмбвҐ† ГУП ММ ХП1_cleaned: 1256-30-ПЗ3/СЃ£Ђ†бЃҐ†≠®• бваЃ®в•ЂмбвҐ† ГУП ММ ХП1_cleaned.md
          - ХЃ§л≠б™®© °гЂмҐ†а, 6-2 - Ѓвз•в ѓЃ Ґ®°а†ж®пђ Ѓв 2024-04-26 (1)_cleaned: 1256-30-ПЗ3/ХЃ§л≠б™®© °гЂмҐ†а, 6-2 - Ѓвз•в ѓЃ Ґ®°а†ж®пђ Ѓв 2024-04-26 (1)_cleaned.md
          - ЭЗ Ходынский Бульвар_cleaned: 1256-30-ПЗ3/ЭЗ Ходынский Бульвар_cleaned.md
      - 1256-30-ПЗ4:
          - 1256-30-ПЗ4: 1256-30-ПЗ4/1256-30-ПЗ4.md
          - МКЭ-30-729.24_cleaned: 1256-30-ПЗ4/МКЭ-30-729.24_cleaned.md
          - ПаЃвЃ™ЃЂ ГЗК ХП_cleaned: 1256-30-ПЗ4/ПаЃвЃ™ЃЂ ГЗК ХП_cleaned.md
          - СЃ§•а¶†≠®• вЃђ†_cleaned: 1256-30-ПЗ4/СЃ§•а¶†≠®• вЃђ†_cleaned.md
          - СТУ 100-24_cleaned: 1256-30-ПЗ4/СТУ 100-24_cleaned.md
      - 1256-30-ПЗ5:
          - 1256-30-ПЗ5: 1256-30-ПЗ5/1256-30-ПЗ5.md
          - З†™Ђоз•≠®• МЧС_cleaned: 1256-30-ПЗ5/З†™Ђоз•≠®• МЧС_cleaned.md
          - СЃ§•а¶†≠®• вЃђ†_cleaned: 1256-30-ПЗ5/СЃ§•а¶†≠®• вЃђ†_cleaned.md
          - СТУ ХЃ§л≠б™Ѓ• ѓЃЂ•: 1256-30-ПЗ5/СТУ ХЃ§л≠б™Ѓ• ѓЃЂ•.md
          - СТУ ХЃ§л≠б™Ѓ• ѓЃЂ•_cleaned: 1256-30-ПЗ5/СТУ ХЃ§л≠б™Ѓ• ѓЃЂ•_cleaned.md
      - 29899-ХП3-ПД-КВ-ОПЗ:
          - 00_ХП3_ПД-КВ-ПЗ_Титул-Rev-0.0: 29899-ХП3-ПД-КВ-ОПЗ/00_ХП3_ПД-КВ-ПЗ_Титул-Rev-0.0.md
          - 01_ХП3_ПД-КВ-ПЗ-Состав томa: 29899-ХП3-ПД-КВ-ОПЗ/01_ХП3_ПД-КВ-ПЗ-Состав томa.md
          - 02_ХП3_ПД-КВ-ПЗ-Пояснительная записка-Rev-0.11: 29899-ХП3-ПД-КВ-ОПЗ/02_ХП3_ПД-КВ-ПЗ-Пояснительная записка-Rev-0.11.md
      - Документация:
          - 01-01-00-01-00 ПЗ.СП_cleaned: Документация/01-01-00-01-00 ПЗ.СП_cleaned.md
          - 01-01-00-02-00 ПЗ_cleaned: Документация/01-01-00-02-00 ПЗ_cleaned.md
          - 01-01-00-02-11 ОПЗ_cleaned: Документация/01-01-00-02-11 ОПЗ_cleaned.md
          - 07-23-НПО-ПЗ_cleaned: Документация/07-23-НПО-ПЗ_cleaned.md
          - 1-2-2022-3-П-ПЗ_cleaned: Документация/1-2-2022-3-П-ПЗ_cleaned.md
          - 1.2_29899-ХП3-ПД-КВ-ОПЗ_cleaned: Документация/1.2_29899-ХП3-ПД-КВ-ОПЗ_cleaned.md
          - 102-24-ГК-ПЗ_cleaned: Документация/102-24-ГК-ПЗ_cleaned.md
          - 102_24-ГК-ОПЗ.2-1_cleaned: Документация/102_24-ГК-ОПЗ.2-1_cleaned.md
          - 1256-30-ПЗ3.1_cleaned: Документация/1256-30-ПЗ3.1_cleaned.md
          - 1256-30-ПЗ3.2_cleaned: Документация/1256-30-ПЗ3.2_cleaned.md
          - 560-3-ПДD-П3.2_cleaned: Документация/560-3-ПДD-П3.2_cleaned.md
          - 560-3-ПДD-ПЗ.1 (В.1)_cleaned: Документация/560-3-ПДD-ПЗ.1 (В.1)_cleaned.md
          - 560-3-ПДD-ПЗ.1_cleaned: Документация/560-3-ПДD-ПЗ.1_cleaned.md
          - KWA-2412-МН1-П-ГП-ПЗ_cleaned: Документация/KWA-2412-МН1-П-ГП-ПЗ_cleaned.md
          - KWA-2412-МН2-П-ГП-ПЗ_cleaned: Документация/KWA-2412-МН2-П-ГП-ПЗ_cleaned.md
          - KWA-№04032024-КСПРО-КВ-ГП-ПЗ_cleaned: Документация/KWA-№04032024-КСПРО-КВ-ГП-ПЗ_cleaned.md
          - KWA-№2405СКЛ.ЖК-ГП-ПЗ_cleaned: Документация/KWA-№2405СКЛ.ЖК-ГП-ПЗ_cleaned.md
          - К11-09-04-2021-ПЗ1_cleaned: Документация/К11-09-04-2021-ПЗ1_cleaned.md
          - К11-09-04-2021-ПЗ2_cleaned: Документация/К11-09-04-2021-ПЗ2_cleaned.md
          - МР-1555-00-ПЗ1_cleaned: Документация/МР-1555-00-ПЗ1_cleaned.md
          - МР-1555-00-ПЗ2_cleaned: Документация/МР-1555-00-ПЗ2_cleaned.md
          - МР-1555-00-ПЗ3.1_cleaned: Документация/МР-1555-00-ПЗ3.1_cleaned.md
          - МР-1555-00-ПЗ3.2_cleaned: Документация/МР-1555-00-ПЗ3.2_cleaned.md
          - МР-1555-00-ПЗ3_cleaned: Документация/МР-1555-00-ПЗ3_cleaned.md
      - Сравнение разных версий:
          - [v2] 29900-ПД-КВ-АР1_cleaned: Сравнение разных версий/[v2] 29900-ПД-КВ-АР1_cleaned.md
          - [v2] 29900-ПД-КВ-ОПЗ_cleaned: Сравнение разных версий/[v2] 29900-ПД-КВ-ОПЗ_cleaned.md
          - [v3] 29900-ПД-КВ-КР2.1_cleaned: Сравнение разных версий/[v3] 29900-ПД-КВ-КР2.1_cleaned.md
          - [v3] 29900-ПД-КВ-ПЗУ_cleaned: Сравнение разных версий/[v3] 29900-ПД-КВ-ПЗУ_cleaned.md
          - [v5] 29900-ПД-КВ-АР1 (1)_cleaned: Сравнение разных версий/[v5] 29900-ПД-КВ-АР1 (1)_cleaned.md
          - [v7] 29900-ПД-КВ-КР2.1_cleaned: Сравнение разных версий/[v7] 29900-ПД-КВ-КР2.1_cleaned.md
          - [v7] 29900-ПД-КВ-ОПЗ (1)_cleaned: Сравнение разных версий/[v7] 29900-ПД-КВ-ОПЗ (1)_cleaned.md
          - [v8] 29900-ПД-КВ-ПЗУ (1)_cleaned: Сравнение разных версий/[v8] 29900-ПД-КВ-ПЗУ (1)_cleaned.md
