site_name: Документация
site_url: https://polekhina01.github.io/
site_description: Автоматически генерируемая документация
repo_url: https://github.com/polekhina01/polekhina01.github.io
repo_name: polekhina01/polekhina01.github.io
use_directory_urls: false
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  features:
  - navigation.tabs
  - navigation.sections
  - search.suggest
  - search.highlight
plugins:
- search:
    lang:
    - ru
    - en
    separator: '[\s\-\.]+'
markdown_extensions:
- attr_list
- toc:
    permalink: true
    toc_depth: 2-3
- admonition
- pymdownx.highlight
- pymdownx.superfences
nav:
- Главная: index.md
- Документы:
  - 10 23 КП П ПЗ:
    - 0 Титульный лист МТ: 10-23_КП-П-ПЗ/0_Титульный_лист_МТ.md
    - 1 Справка ГИПа 2021.03.17: 10-23_КП-П-ПЗ/1_Справка_ГИПа-2021.03.17.md
    - 2 Содержание МТ 2021.11.17: 10-23_КП-П-ПЗ/2_Содержание_МТ-2021.11.17.md
    - 3 Пояснительная записка КПЛН МТ 2024.06.28: 10-23_КП-П-ПЗ/3_Пояснительная_записка_КПЛН_МТ_2024.06.28.md
  - 1076 01 ПЗ1:
    - 1076 01 ПЗ1: 1076-01-ПЗ1/1076-01-ПЗ1_.md
    - 1076 01 ПЗ1 cleaned: 1076-01-ПЗ1/1076-01-ПЗ1_cleaned.md
    - 20231117 ЗУП Этап2 ver1: 1076-01-ПЗ1/20231117_ЗУП_Этап2_ver1.md
    - Титул лист.1 1076 01 ПЗ1: 1076-01-ПЗ1/Титул лист.1 1076-01-ПЗ1.md
  - 1076 01 ПЗ2:
    - 1076 01 ПЗ2 cleaned: 1076-01-ПЗ2/1076-01-ПЗ2_cleaned.md
    - 1076 01 ПЗ2 rev2: 1076-01-ПЗ2/1076-01-ПЗ2_rev2.md
  - 1256 30 ПЗ1:
    - 1256 30 ПЗ1. СП: 1256-30-ПЗ1/1256-30-ПЗ1. СП.md
    - 1256 30 ПЗ1 titul Sign cleaned: 1256-30-ПЗ1/1256-30-ПЗ1_titul_Sign_cleaned.md
    - 1256 30 ПЗ1 содержание cleaned: 1256-30-ПЗ1/1256-30-ПЗ1_содержание_cleaned.md
    - Выписка НОПРИЗ Романова И.П. cleaned: 1256-30-ПЗ1/Выписка НОПРИЗ Романова И.П._cleaned.md
  - 1256 30 ПЗ2:
    - 1256 30 ПЗ2: 1256-30-ПЗ2/1256-30-ПЗ2.md
    - 1256 30 ПЗ2 cleaned: 1256-30-ПЗ2/1256-30-ПЗ2_cleaned.md
    - 1256 30 ПЗ2 titul Sign cleaned: 1256-30-ПЗ2/1256-30-ПЗ2_titul_Sign_cleaned.md
  - 1256 30 ПЗ3:
    - ИИ:
      - ИГДИ заключение cleaned: 1256-30-ПЗ3/ИИ/ИГДИ_заключение_cleaned.md
      - ИГДИ отчет тит cleaned: 1256-30-ПЗ3/ИИ/ИГДИ_отчет_тит_cleaned.md
      - ИГДИ подписи cleaned: 1256-30-ПЗ3/ИИ/ИГДИ_подписи_cleaned.md
      - ИГДИ программа тит cleaned: 1256-30-ПЗ3/ИИ/ИГДИ_программа_тит_cleaned.md
      - ИГДИ ТЗ на ИИ cleaned: 1256-30-ПЗ3/ИИ/ИГДИ_ТЗ на ИИ_cleaned.md
      - ИГИ заключение cleaned: 1256-30-ПЗ3/ИИ/ИГИ_заключение_cleaned.md
      - ИГИ отчет тит cleaned: 1256-30-ПЗ3/ИИ/ИГИ_отчет_тит_cleaned.md
      - ИГИ программа тит cleaned: 1256-30-ПЗ3/ИИ/ИГИ_программа_тит_cleaned.md
      - ИГИ ТЗ на ИИ cleaned: 1256-30-ПЗ3/ИИ/ИГИ_ТЗ на ИИ_cleaned.md
      - ИЭИ заключение cleaned: 1256-30-ПЗ3/ИИ/ИЭИ_заключение_cleaned.md
      - ИЭИ отчет тит cleaned: 1256-30-ПЗ3/ИИ/ИЭИ_отчет_тит_cleaned.md
      - ИЭИ программа тит cleaned: 1256-30-ПЗ3/ИИ/ИЭИ_программа_тит_cleaned.md
      - ИЭИ ТЗ на ИИ cleaned: 1256-30-ПЗ3/ИИ/ИЭИ_ТЗ на ИИ_cleaned.md
    - Приложение №:
      - PDF:
        - 10 cleaned: 1256-30-ПЗ3/Приложение №/PDF/10_cleaned.md
        - 11 cleaned: 1256-30-ПЗ3/Приложение №/PDF/11_cleaned.md
        - 12 cleaned: 1256-30-ПЗ3/Приложение №/PDF/12_cleaned.md
        - 13 cleaned: 1256-30-ПЗ3/Приложение №/PDF/13_cleaned.md
        - 14 cleaned: 1256-30-ПЗ3/Приложение №/PDF/14_cleaned.md
        - 15 cleaned: 1256-30-ПЗ3/Приложение №/PDF/15_cleaned.md
        - 16 cleaned: 1256-30-ПЗ3/Приложение №/PDF/16_cleaned.md
        - 17 cleaned: 1256-30-ПЗ3/Приложение №/PDF/17_cleaned.md
        - 18 cleaned: 1256-30-ПЗ3/Приложение №/PDF/18_cleaned.md
        - 19 cleaned: 1256-30-ПЗ3/Приложение №/PDF/19_cleaned.md
        - 1 cleaned: 1256-30-ПЗ3/Приложение №/PDF/1_cleaned.md
        - 20 cleaned: 1256-30-ПЗ3/Приложение №/PDF/20_cleaned.md
        - 21 cleaned: 1256-30-ПЗ3/Приложение №/PDF/21_cleaned.md
        - 22 cleaned: 1256-30-ПЗ3/Приложение №/PDF/22_cleaned.md
        - 23 cleaned: 1256-30-ПЗ3/Приложение №/PDF/23_cleaned.md
        - 24 cleaned: 1256-30-ПЗ3/Приложение №/PDF/24_cleaned.md
        - 25 cleaned: 1256-30-ПЗ3/Приложение №/PDF/25_cleaned.md
        - 26 cleaned: 1256-30-ПЗ3/Приложение №/PDF/26_cleaned.md
        - 27 cleaned: 1256-30-ПЗ3/Приложение №/PDF/27_cleaned.md
        - 28 cleaned: 1256-30-ПЗ3/Приложение №/PDF/28_cleaned.md
        - 29 cleaned: 1256-30-ПЗ3/Приложение №/PDF/29_cleaned.md
        - 2 cleaned: 1256-30-ПЗ3/Приложение №/PDF/2_cleaned.md
        - 30 cleaned: 1256-30-ПЗ3/Приложение №/PDF/30_cleaned.md
        - 31 cleaned: 1256-30-ПЗ3/Приложение №/PDF/31_cleaned.md
        - 32 cleaned: 1256-30-ПЗ3/Приложение №/PDF/32_cleaned.md
        - 33 cleaned: 1256-30-ПЗ3/Приложение №/PDF/33_cleaned.md
        - 34 cleaned: 1256-30-ПЗ3/Приложение №/PDF/34_cleaned.md
        - 35 cleaned: 1256-30-ПЗ3/Приложение №/PDF/35_cleaned.md
        - 36 cleaned: 1256-30-ПЗ3/Приложение №/PDF/36_cleaned.md
        - 37 cleaned: 1256-30-ПЗ3/Приложение №/PDF/37_cleaned.md
        - 38 cleaned: 1256-30-ПЗ3/Приложение №/PDF/38_cleaned.md
        - 39 cleaned: 1256-30-ПЗ3/Приложение №/PDF/39_cleaned.md
        - 3 cleaned: 1256-30-ПЗ3/Приложение №/PDF/3_cleaned.md
        - 40 cleaned: 1256-30-ПЗ3/Приложение №/PDF/40_cleaned.md
        - 41 cleaned: 1256-30-ПЗ3/Приложение №/PDF/41_cleaned.md
        - 42 cleaned: 1256-30-ПЗ3/Приложение №/PDF/42_cleaned.md
        - 43 cleaned: 1256-30-ПЗ3/Приложение №/PDF/43_cleaned.md
        - 44 cleaned: 1256-30-ПЗ3/Приложение №/PDF/44_cleaned.md
        - 45 cleaned: 1256-30-ПЗ3/Приложение №/PDF/45_cleaned.md
        - 46 cleaned: 1256-30-ПЗ3/Приложение №/PDF/46_cleaned.md
        - 47 cleaned: 1256-30-ПЗ3/Приложение №/PDF/47_cleaned.md
        - 48 cleaned: 1256-30-ПЗ3/Приложение №/PDF/48_cleaned.md
        - 49 cleaned: 1256-30-ПЗ3/Приложение №/PDF/49_cleaned.md
        - 4 cleaned: 1256-30-ПЗ3/Приложение №/PDF/4_cleaned.md
        - 50 cleaned: 1256-30-ПЗ3/Приложение №/PDF/50_cleaned.md
        - 5 cleaned: 1256-30-ПЗ3/Приложение №/PDF/5_cleaned.md
        - 6 cleaned: 1256-30-ПЗ3/Приложение №/PDF/6_cleaned.md
        - 7 cleaned: 1256-30-ПЗ3/Приложение №/PDF/7_cleaned.md
        - 8 cleaned: 1256-30-ПЗ3/Приложение №/PDF/8_cleaned.md
        - 9 cleaned: 1256-30-ПЗ3/Приложение №/PDF/9_cleaned.md
        - Все приложения cleaned: 1256-30-ПЗ3/Приложение №/PDF/Все приложения_cleaned.md
      - Приложение №: 1256-30-ПЗ3/Приложение №/Приложение №.md
    - СРО выписки:
      - 2023.03.14 СРО. Карат 91 cleaned: 1256-30-ПЗ3/СРО выписки/2023.03.14 СРО. Карат-91_cleaned.md
      - 2023.03.20. СРО МГГТ cleaned: 1256-30-ПЗ3/СРО выписки/2023.03.20. СРО МГГТ_cleaned.md
      - 2024.02.19. СРО НПЦ Мир изысканий cleaned: 1256-30-ПЗ3/СРО выписки/2024.02.19. СРО НПЦ Мир изысканий_cleaned.md
      - 2024.02.20. СРО НПЦ Основа cleaned: 1256-30-ПЗ3/СРО выписки/2024.02.20. СРО НПЦ Основа_cleaned.md
      - 2024.02.22. СРО ДМЕ ГРУПП cleaned: 1256-30-ПЗ3/СРО выписки/2024.02.22. СРО ДМЕ ГРУПП_cleaned.md
      - 2024.02.29. СРО З Сойл cleaned: 1256-30-ПЗ3/СРО выписки/2024.02.29. СРО З-Сойл_cleaned.md
      - 2024.02.29. СРО НИИТДХ cleaned: 1256-30-ПЗ3/СРО выписки/2024.02.29. СРО НИИТДХ_cleaned.md
      - 2024.03.11. СРО Инсоляция и КЕО cleaned: 1256-30-ПЗ3/СРО выписки/2024.03.11. СРО Инсоляция и КЕО_cleaned.md
      - 2024.03.11. СРО Симпл Проект cleaned: 1256-30-ПЗ3/СРО выписки/2024.03.11. СРО Симпл-Проект_cleaned.md
      - 2024.03.12 СРО Проектное бюро Апекс cleaned: 1256-30-ПЗ3/СРО выписки/2024.03.12 СРО Проектное бюро Апекс_cleaned.md
      - 2024.03.15. СРО Ф Метрикс cleaned: 1256-30-ПЗ3/СРО выписки/2024.03.15. СРО Ф-Метрикс_cleaned.md
    - ТУ:
      - Договор № ИА 23 302 16175 113433 от 28 09 2023 подп cleaned: 1256-30-ПЗ3/ТУ/_Договор_№_ИА_23_302_16175_113433_от_28_09_2023_подп_cleaned.md
      - Договор №10 11 24 187 подписан cleaned: 1256-30-ПЗ3/ТУ/Договор №10-11-24-187_подписан_cleaned.md
      - НВ Дог. 18006 ДП В от 21.03.2024 подп. cleaned: 1256-30-ПЗ3/ТУ/НВ_Дог. 18006 ДП-В от 21.03.2024_подп._cleaned.md
      - НК Дог. 18007 ДП К от 22.04.2024 подп. cleaned: 1256-30-ПЗ3/ТУ/НК_Дог. 18007 ДП-К от 22.04.2024_подп._cleaned.md
      - Согл №1 к дог № ИА 23 302 16175113433 от 01 04 2024 подписан cleaned: 1256-30-ПЗ3/ТУ/Согл_№1_к_дог_№_ИА_23_302_16175113433_от_01_04_2024_подписан_cleaned.md
      - ТУ № 111 ОП (Iptv, пд, тлф, радио)   Ходынский бульвар, з.у. 6 2 cleaned: 1256-30-ПЗ3/ТУ/ТУ № 111-ОП (Iptv, пд, тлф, радио) - Ходынский бульвар, з.у. 6-2_cleaned.md
      - ЭС ТУ к Согл №1 к дог № ИА 23 302 16175(113433) от 01.04.2024 подп. cleaned: 1256-30-ПЗ3/ТУ/ЭС_ТУ к Согл №1 к дог № ИА-23-302-16175(113433) от 01.04.2024_подп._cleaned.md
      - №ТП 0172 24 от 22.03.2024 cleaned: 1256-30-ПЗ3/ТУ/№ТП-0172-24 от 22.03.2024_cleaned.md
    - 0869 РФ О РСПИ Ходынский б р, уч. 6.2 cleaned: 1256-30-ПЗ3/0869_РФ-О-РСПИ_Ходынский б-р, уч. 6.2_cleaned.md
    - 1256 30 ПЗ3.1: 1256-30-ПЗ3/1256-30-ПЗ3.1.md
    - 1256 30 ПЗ3.1 titul Sign cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.1_titul_Sign_cleaned.md
    - 1256 30 ПЗ3.1 содержание cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.1_содержание_cleaned.md
    - 1256 30 ПЗ3.2: 1256-30-ПЗ3/1256-30-ПЗ3.2.md
    - 1256 30 ПЗ3.2 titul Sign cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.2_titul_Sign_cleaned.md
    - 1256 30 ПЗ3.2 содержание cleaned: 1256-30-ПЗ3/1256-30-ПЗ3.2_содержание_cleaned.md
    - 1256 ЗНП для МГЭ: 1256-30-ПЗ3/1256_ЗНП для МГЭ.md
    - 1256 ЗНП для МГЭ cleaned: 1256-30-ПЗ3/1256_ЗНП для МГЭ_cleaned.md
    - 1256 ЗНП для МГЭ титул   подписан cleane: 1256-30-ПЗ3/1256_ЗНП для МГЭ_титул - подписан_cleane.md
    - 16 13 3322икоп cleaned: 1256-30-ПЗ3/16-13-3322икоп_cleaned.md
    - 230818 Дог. аренды ЗУ 17079 Скиф Инвест cleaned: 1256-30-ПЗ3/230818_Дог. аренды ЗУ 17079 Скиф-Инвест_cleaned.md
    - 230823 Справка о климатической характеристике cleaned: 1256-30-ПЗ3/230823_Справка о климатической характеристике_cleaned.md
    - 230823 Справка о фоновых концентрациях cleaned: 1256-30-ПЗ3/230823_Справка о фоновых концентрациях_cleaned.md
    - 230914 Справка об установленных СЗЗ cleaned: 1256-30-ПЗ3/230914_Справка об установленных СЗЗ_cleaned.md
    - 230928 ТУ Россети № И 23 00 113433 102 cleaned: 1256-30-ПЗ3/230928_ТУ Россети № И-23-00-113433_102_cleaned.md
    - 231030 Справка об интенсивности движения транспорта cleaned: 1256-30-ПЗ3/231030_Справка об интенсивности движения транспорта_cleaned.md
    - 231102 Выписка из ЕГРН на ЗУ 77 09 0005007 17079 с изъятым куском cleaned: 1256-30-ПЗ3/231102_Выписка из ЕГРН на ЗУ 77 09 0005007 17079 с изъятым куском_cleaned.md
    - 231130 Нагрузки на офисы (ЭОМ предложение): 1256-30-ПЗ3/231130_Нагрузки на офисы (ЭОМ предложение).md
    - 231130 Нагрузки на офисы (ЭОМ предложение) cleaned: 1256-30-ПЗ3/231130_Нагрузки на офисы (ЭОМ предложение)_cleaned.md
    - 240618 Нагрузки на общественные помещения (ЭОМ) cleaned: 1256-30-ПЗ3/240618_Нагрузки на общественные помещения (ЭОМ)_cleaned.md
    - 240624 КС ПРО МГЭ   инфо о сносе cleaned: 1256-30-ПЗ3/240624_КС-ПРО МГЭ - инфо о сносе_cleaned.md
    - Акт с приложениями Ходынский бульвар зу 6.2 cleaned: 1256-30-ПЗ3/Акт с приложениями_Ходынский бульвар зу 6.2_cleaned.md
    - АО  СКИФ ИНВЕСТ  Номер ТУ 69850 Рег номер ТУ 112 25 1488 24 (1) cleaned: 1256-30-ПЗ3/АО _СКИФ ИНВЕСТ__Номер_ТУ_69850_Рег_номер_ТУ_112-25-1488_24 (1)_cleaned.md
    - Бренд лист cleaned: 1256-30-ПЗ3/Бренд-лист_cleaned.md
    - Заключение Ходынский бульвар cleaned: 1256-30-ПЗ3/Заключение Ходынский бульвар_cleaned.md
    - исх. №1314 от 11.06.2024 О нетоксичности применяемых строй материалов н... cleaned: 1256-30-ПЗ3/исх. №1314 от 11.06.2024_О нетоксичности применяемых строй материалов н..._cleaned.md
    - КС про Ходынский бул. з у 6 2 cleaned: 1256-30-ПЗ3/КС-про Ходынский бул. з-у 6-2_cleaned.md
    - Письмо ДКН cleaned: 1256-30-ПЗ3/Письмо ДКН_cleaned.md
    - Приложение 1 ТЗ. Приложение 1. Бренд лист вер.3: 1256-30-ПЗ3/Приложение 1_ТЗ. Приложение 1. Бренд-лист вер.3.md
    - Приложение 1 ТЗ. Приложение 3.3. Нагрузки КР: 1256-30-ПЗ3/Приложение 1_ТЗ. Приложение 3.3. Нагрузки КР.md
    - Протокол ГЗК ХП cleaned: 1256-30-ПЗ3/Протокол ГЗК ХП_cleaned.md
    - РФ 77 4 53 3 48 2024 0330 0 ГПЗУ cleaned: 1256-30-ПЗ3/РФ-77-4-53-3-48-2024-0330-0-ГПЗУ_cleaned.md
    - Согласование строительства ГУП ММ ХП1 cleaned: 1256-30-ПЗ3/Согласование строительства ГУП ММ ХП1_cleaned.md
    - Ходынский бульвар, 6 2   отчет по вибрациям от 2024 04 26 (1) cleaned: 1256-30-ПЗ3/Ходынский бульвар, 6-2 - отчет по вибрациям от 2024-04-26 (1)_cleaned.md
    - ЭЗ Ходынский Бульвар cleaned: 1256-30-ПЗ3/ЭЗ Ходынский Бульвар_cleaned.md
  - 1256 30 ПЗ4:
    - 1256 30 ПЗ4: 1256-30-ПЗ4/1256-30-ПЗ4.md
    - МКЭ 30 729.24 cleaned: 1256-30-ПЗ4/МКЭ-30-729.24_cleaned.md
    - Протокол ГЗК ХП cleaned: 1256-30-ПЗ4/Протокол ГЗК ХП_cleaned.md
    - Содержание тома cleaned: 1256-30-ПЗ4/Содержание тома_cleaned.md
    - СТУ 100 24 cleaned: 1256-30-ПЗ4/СТУ 100-24_cleaned.md
  - 1256 30 ПЗ5:
    - 1256 30 ПЗ5: 1256-30-ПЗ5/1256-30-ПЗ5.md
    - Заключение МЧС cleaned: 1256-30-ПЗ5/Заключение МЧС_cleaned.md
    - Содержание тома cleaned: 1256-30-ПЗ5/Содержание тома_cleaned.md
    - СТУ Ходынское поле: 1256-30-ПЗ5/СТУ Ходынское поле.md
    - СТУ Ходынское поле cleaned: 1256-30-ПЗ5/СТУ Ходынское поле_cleaned.md
  - 29899 ХП3 ПД КВ ОПЗ:
    - 00 ХП3 ПД КВ ПЗ Титул Rev 0.0: 29899-ХП3-ПД-КВ-ОПЗ/00_ХП3_ПД-КВ-ПЗ_Титул-Rev-0.0.md
    - 01 ХП3 ПД КВ ПЗ Состав томa: 29899-ХП3-ПД-КВ-ОПЗ/01_ХП3_ПД-КВ-ПЗ-Состав томa.md
    - 02 ХП3 ПД КВ ПЗ Пояснительная записка Rev 0.11: 29899-ХП3-ПД-КВ-ОПЗ/02_ХП3_ПД-КВ-ПЗ-Пояснительная записка-Rev-0.11.md
  - Документация:
    - 01 01 00 01 00 ПЗ.СП cleaned: Документация/01-01-00-01-00 ПЗ.СП_cleaned.md
    - 01 01 00 02 00 ПЗ cleaned: Документация/01-01-00-02-00 ПЗ_cleaned.md
    - 01 01 00 02 11 ОПЗ cleaned: Документация/01-01-00-02-11 ОПЗ_cleaned.md
    - 07 23 НПО ПЗ cleaned: Документация/07-23-НПО-ПЗ_cleaned.md
    - 1 2 2022 3 П ПЗ cleaned: Документация/1-2-2022-3-П-ПЗ_cleaned.md
    - 1.2 29899 ХП3 ПД КВ ОПЗ cleaned: Документация/1.2_29899-ХП3-ПД-КВ-ОПЗ_cleaned.md
    - 102 24 ГК ПЗ cleaned: Документация/102-24-ГК-ПЗ_cleaned.md
    - 102 24 ГК ОПЗ.2 1 cleaned: Документация/102_24-ГК-ОПЗ.2-1_cleaned.md
    - 1256 30 ПЗ3.1 cleaned: Документация/1256-30-ПЗ3.1_cleaned.md
    - 1256 30 ПЗ3.2 cleaned: Документация/1256-30-ПЗ3.2_cleaned.md
    - 560 3 ПДD П3.2 cleaned: Документация/560-3-ПДD-П3.2_cleaned.md
    - 560 3 ПДD ПЗ.1 (В.1) cleaned: Документация/560-3-ПДD-ПЗ.1 (В.1)_cleaned.md
    - 560 3 ПДD ПЗ.1 cleaned: Документация/560-3-ПДD-ПЗ.1_cleaned.md
    - KWA 2412 МН1 П ГП ПЗ cleaned: Документация/KWA-2412-МН1-П-ГП-ПЗ_cleaned.md
    - KWA 2412 МН2 П ГП ПЗ cleaned: Документация/KWA-2412-МН2-П-ГП-ПЗ_cleaned.md
    - KWA №04032024 КСПРО КВ ГП ПЗ cleaned: Документация/KWA-№04032024-КСПРО-КВ-ГП-ПЗ_cleaned.md
    - KWA №2405СКЛ.ЖК ГП ПЗ cleaned: Документация/KWA-№2405СКЛ.ЖК-ГП-ПЗ_cleaned.md
    - К11 09 04 2021 ПЗ1 cleaned: Документация/К11-09-04-2021-ПЗ1_cleaned.md
    - К11 09 04 2021 ПЗ2 cleaned: Документация/К11-09-04-2021-ПЗ2_cleaned.md
    - МР 1555 00 ПЗ1 cleaned: Документация/МР-1555-00-ПЗ1_cleaned.md
    - МР 1555 00 ПЗ2 cleaned: Документация/МР-1555-00-ПЗ2_cleaned.md
    - МР 1555 00 ПЗ3.1 cleaned: Документация/МР-1555-00-ПЗ3.1_cleaned.md
    - МР 1555 00 ПЗ3.2 cleaned: Документация/МР-1555-00-ПЗ3.2_cleaned.md
    - МР 1555 00 ПЗ3 cleaned: Документация/МР-1555-00-ПЗ3_cleaned.md
  - Сравнение разных версий:
    - 29900 ПД КВ АР1 diff: Сравнение разных версий/29900-ПД-КВ-АР1 diff.html
    - 29900 ПД КВ КР2.1 diff: Сравнение разных версий/29900-ПД-КВ-КР2.1 diff.html
    - 29900 ПД КВ ОПЗ diff: Сравнение разных версий/29900-ПД-КВ-ОПЗ diff.html
    - 29900 ПД КВ ПЗУ diff: Сравнение разных версий/29900-ПД-КВ-ПЗУ diff.html
    - '[v2] 29900 ПД КВ АР1 cleaned': Сравнение разных версий/[v2] 29900-ПД-КВ-АР1_cleaned.md
    - '[v2] 29900 ПД КВ ОПЗ cleaned': Сравнение разных версий/[v2] 29900-ПД-КВ-ОПЗ_cleaned.md
    - '[v3] 29900 ПД КВ КР2.1 cleaned': Сравнение разных версий/[v3] 29900-ПД-КВ-КР2.1_cleaned.md
    - '[v3] 29900 ПД КВ ПЗУ cleaned': Сравнение разных версий/[v3] 29900-ПД-КВ-ПЗУ_cleaned.md
    - '[v5] 29900 ПД КВ АР1 (1) cleaned': Сравнение разных версий/[v5] 29900-ПД-КВ-АР1 (1)_cleaned.md
    - '[v7] 29900 ПД КВ КР2.1 cleaned': Сравнение разных версий/[v7] 29900-ПД-КВ-КР2.1_cleaned.md
    - '[v7] 29900 ПД КВ ОПЗ (1) cleaned': Сравнение разных версий/[v7] 29900-ПД-КВ-ОПЗ (1)_cleaned.md
    - '[v8] 29900 ПД КВ ПЗУ (1) cleaned': Сравнение разных версий/[v8] 29900-ПД-КВ-ПЗУ (1)_cleaned.md
